### ISSUE TITLE
Which is the parent of this POSHSPY

### ISSUE THREAD

**Issue by nguyenl95** [matthewdunwoody/POSHSPY#1]
As title, curious about who's parent of this powershell?

**Comment by matthewdunwoody** [comment]
Mother Russia. See: https://www.fireeye.com/blog/threat-research/2017/03/dissecting_one_ofap.html

**Comment by nguyenl95** [comment]
@matthewdunwoody : Thanks for nice read, but I'm trying to ask which file generating this WMI backdoor?
I downloaded several samples from [here](http://contagiodump.blogspot.com/2017/03/part-ii-apt29-russian-apt-including.html) but none of them contain powershell or its base64 encoded version.
I'm curious here, it would be nice if you could share the sample.

**Comment by matthewdunwoody** [comment]
It was installed using a PowerShell script run on a remote system. We
didn't recover the file but identified evidence of it in PowerShell logs.
It simply ran wmi commands to write the properties and create the event
subscription.
